### ISSUE TITLE
webpack2

### ISSUE THREAD

**Issue by cescoferraro** [olegstepura/typed-css-modules-loader#10]
Stack
```
ERROR in ./~/css-loader?sourceMap&modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5!./~/sass-loader?sourceMap!./~/typed-css-modules!./~/sass-loader!./src/sass/main.scss
Module build failed: TypeError: Cannot call a class as a function
    at _classCallCheck (/home/cescoferraro/code/go/src/github.com/cescoferraro/spotify/node_modules/typed-css-modules/lib/dtsCreator.js:46:99)
    at Object.DtsCreator (/home/cescoferraro/code/go/src/github.com/cescoferraro/spotify/node_modules/typed-css-modules/lib/dtsCreator.js:123:5)
 @ ./src/sass/main.scss 4:14-312
 @ ./src/ts/shell.tsx
 @ ./src/ts/app.tsx
```

preloader
```
{
            enforce: 'pre',
            test: /\.scss$/,
            exclude: /node_modules/,
            loaders: ['typed-css-modules', 'sass-loader']
        }
```

**Comment by olegstepura** [comment]
According to stack trace issue is related to `dtsCreator` which is part of [`typed-css-modules`](https://github.com/Quramy/typed-css-modules/blob/master/src/dtsCreator.js). Please report there. Not related here.
